#!/bin/bash
# to test the functionnality :
# yunohost app remove homeassistant

source _common.sh
source /usr/share/yunohost/helpers

# retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)
port=$(ynh_app_setting_get $app port)

# definie useful vars
final_path="/opt/yunohost/$app"
home_path="/home/$app"

# remove metapackage and its dependencies
ynh_remove_app_dependencies

# remove the app directory securely
ynh_secure_remove "$final_path"

# remove the dedicated nginx config
ynh_remove_nginx_config

# remove a directory securely
ynh_secure_remove "$home_path"

# remove service from admin panel
if yunohost service status | grep -q "$app@$app"
then
	yunohost service remove "$app@$app"
fi

# remove systemd service
ynh_system_reload --service_name="$app@$app" --action=stop
ynh_system_reload --service_name="$app@$app" --action=disable
ynh_secure_remove "/etc/systemd/system/$app.service"

# close port
ynh_exec_fully_quiet yunohost firewall disallow TCP $port

# delete a system user
ynh_system_user_delete "$app"
