name: Create master promotion pull request
on:
  # Allow to manually trigger the workflow
  workflow_dispatch:
  # Run it when when someone pushes to testing
  push:
    branches:
      - testing
jobs:
  masterPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin testing:testing
          git reset --hard testing
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: master-promotion
          title: 'Upgrade master from testing'
          body: |
            Upgrade master from testing
